#!/bin/bash
# 本地同步指南 - 在你的 Mac 上操作

echo "=========================================="
echo "本地 Mac 更新数据 + 同步到服务器"
echo "=========================================="
echo ""
echo "步骤 1: Mac 上运行数据更新"
echo "  cd ~/github/stock-quant/stock-quant/python"
echo "  ./scripts/start.sh update"
echo ""
echo "步骤 2: 同步到服务器 (任选一种)"
echo ""
echo "  方式 A - scp:"
echo "    scp ~/github/stock-quant/stock-quant/python/data/*.csv SERVER_IP:/root/github/stock-quant/stock-quant/python/data/"
echo ""
echo "  方式 B - rsync (推荐，增量同步):"
echo "    rsync -avz ~/github/stock-quant/stock-quant/python/data/*.csv SERVER_IP:/root/github/stock-quant/stock-quant/python/data/"
echo ""
echo "  方式 C - 手动上传:"
echo "    打开 SFTP/FTP 工具，上传 CSV 文件到服务器"
echo ""
echo "=========================================="
echo "设置定时任务 (可选)"
echo "=========================================="
echo ""
echo "Mac crontab - 每晚自动同步:"
echo "  0 21 * * 1-5 rsync -avz ~/github/stock-quant/stock-quant/python/data/*.csv SERVER_IP:/root/github/stock-quant/stock-quant/python/data/"
